kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-retry
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: OMSORGSOPPTJENING_TOPIC
      value: pensjonopptjening.omsorgsopptjening
    - name: OMSORGSOPPTJENING_RETRY_GROUP_ID
      value: omsorgsopptjening-retry-group
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  image: {{ image }}
  ingresses:
    - https://omsorgsopptjening-retry.dev.intern.nav.no
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "10"
      memory: "4096Mi"
    requests:
      cpu: "1"
      memory: "2048Mi"